-- Align vector storage with nomic-embed-text, which returns 768 dimensions.
--
-- Existing vectors from a different dimensional model cannot be converted
-- meaningfully. Preserve chunks, clear incompatible embeddings, and rebuild
-- the vector column and HNSW index.

DELETE FROM embeddings;

DROP INDEX IF EXISTS idx_embeddings_vector_hnsw;

ALTER TABLE embeddings
    ALTER COLUMN embedding TYPE vector(768)
    USING embedding::vector(768);

ALTER TABLE embeddings
    DROP CONSTRAINT IF EXISTS chk_embedding_dimension_matches;

ALTER TABLE embeddings
    ADD CONSTRAINT chk_embedding_dimension_matches
    CHECK (dimension = 768);

CREATE INDEX idx_embeddings_vector_hnsw ON embeddings
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

COMMENT ON COLUMN embeddings.embedding IS '768-dimensional vector generated by nomic-embed-text';
